# its just for trigger something
sudo: false
dist: trusty

addons_shortcuts:
  addons_gcc5: &gcc5
    apt:
      sources:  [ 'ubuntu-toolchain-r-test']
      packages: [ 'gcc-5','g++-5', 'gperf']

language: cpp

matrix:
  include:
    - os: linux
      env: _CXX=g++-5 _CC=gcc-5 JOBS=1
      addons: *gcc5


before_install:
  #- sudo apt-get -qq update
  #- sudo apt-get install -y libxml2-dev

addons:
  apt:
    packages:
      - gperf


install:
  # /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
  - false || [ -z "$_CXX" ] || export CXX=${_CXX}
  - false || [ -z "$_CC" ] || export CC=${_CC}
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

script:
  - mkdir build
  - cd build
  - cmake .. && make -j${JOBS} VERBOSE=1
  - ./test/run_all_tests --filter -client
  
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
